# 1. Credenciales de la Base de Datos
spring.datasource.url=jdbc:postgresql://ep-royal-bread-am2x71ls.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_0iHCQuI5bomZ
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Configuracion del Motor ORM (Hibernate)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# "none" significa que Java NO alterara ni borrara tu tabla telemetria_buses, solo la leera
spring.jpa.hibernate.ddl-auto=none
# Esto imprimira en tu consola las ordenes SQL que Java ejecute por debajo (Excelente para depurar)
spring.jpa.show-sql=true